#!/bin/env python3

"""
Emulator
"""

import kernel

init = """
literal 1
open
literal 0
load ref _sp
literal 10
sub
literal 5
if zero val _ip

literal 1
close
"""

def main():
	k = kernel.kernel(init)

if __name__ == "__main__":
	main()
