#!/bin/env python3

"""
Emulator
"""

import kernel

init = """
open stdout
push literal 0 -
push literal a -
ifzero sub - _ip 4
	push deref _fp 1 -
	push literal 1 -
	copy add - _fp 1
	pop 2
	copy literal ffff - stdout:0
copy ref code:3 _ip
pop 2
close stdout
"""

def main():
	k = kernel.kernel(init)

if __name__ == "__main__":
	main()
