#!/usr/bin/env python3
import serl

f = serl.parse(r"""
item1
? item2.key1.item1
  item2.key1.item2
  : - item2.value1.item1
    - - ? item2.value1.item2.item1.key1.item1
          item2.value1.item2.item1.key1.item2
      - item2.value1.item2.item2
key3: value3

——
  
""")

print(f)

o = ('a',)
o = serl.omap(o)
print(o)
print(serl.dump(o))
