#!/usr/bin/env python3
import asm

a = asm.assembly(r"""
format bin
architecture ir
section code    data align=8
    "mov {_end} _sp \{testlabel} \{data.end}"
  testlabel:
    "mov {_end + 1} _fp"
    "mov {testlabel} _ip"
  end:
section data data align=64
  hello: "hello,      日本語world!\n", 010203afh
    "{2}\{code.end * 2}}\{data.hello}test", {a93dh + hello * code.testlabel}, r"\\\\n", "\n"
    {2**8 - 1}, {a}, "\{a}", "{hello}   \{hello+1}"
    "this is a test\\\"\\", r"a\" simple test\\\"
    0, bh,
    "\u65e5"
  end:
""")

print(a)
