#!/usr/bin/env python3
import grammar

g = grammar.grammar("""
S = production S
S = newline S
S = production
S = newline
  production = string "=" string newline
  production = string "=" empty-string newline
    string = non-terminal string
    string = terminal string
    string = non-terminal
    string = terminal
      non-terminal = "a"
      non-terminal = "b"
      non-terminal = "c"
      non-terminal = "d"
      non-terminal = "e"
      non-terminal = "f"
      non-terminal = "a"
      terminal = 0x22 printable-character 0x22
    empty-string = 0x3b5
    newline = 0xa newline
    newline = 0xa
""")

print(g)
