#!/usr/bin/env python3
import grammar

g = grammar.grammar("""
S = production S
S = newline S
S = production
S = newline
  production = A "=" A newline
    A = string
      string = non-terminal string
      string = terminal string
      string = non-terminal
      string = terminal
    A = empty-string
      empty-string = 03b5
    newline = 0a newline
    newline = 0a
""")

