#!/usr/bin/env python3
import grammar

g = grammar.grammar('''
S = production S
S = newline S
S = production
S = newline
S = ε
  production = string "=" string newline
  production = string "=" empty-string newline
    string = non-terminal string
    string = terminal string
    string = non-terminal
    string = terminal
      non-terminal = "a"
      non-terminal = "b"
      non-terminal = "c"
      non-terminal = "d"
      non-terminal = "e"
      non-terminal = "f"
      non-terminal = "a"
      terminal = 0x22 printable-character 0x22
    empty-string = 0x3b5
    newline = 0xa newline
    newline = 0xa
''')

eg8311 = grammar.grammar('''
S = C A 0x0 D
A 0x0 = 0x0 0x0 A
A D = B D
0x0 B = B 0x0
C B = C A
C A = A
A D = ε
''')

print(eg8311)
