#!/usr/bin/env python3
import serl

f = serl.parse(r"""
item1
? item2.key1.item1
  item2.key1.item2
  : - item2.value1.item1
    - - ? item2.value1.item2.item1.key1.item1
          item2.value1.item2.item1.key1.item2
      - item2.value1.item2.item2
key3: value3
People:
  - name:           Victor van Poppelen
    birthdate:      1991-02-14
    birthplace:     Houten, NL
  - name:           Alexander van Poppelen
    birthdate:      1989-07-29
    birthplace:     Nieuwegein, The Netherlands
  - name:       Jacqueline de Bruin
    birth-name: Jacqueline van Poppelen
    birthdate:  1985-09-07
    nick-names: [ Jackie, Jacko, Jackie Brown ]
——
 
  
""")

print(f)

o = serl.omap(('a', 'b', {'key-c': 'c'}, 'd', {'key-only'}, 'f'))
print(serl.dump(o))
print(o)
