#!/usr/bin/env python3
import asm

a = asm.assembly(r"""
format bin
architecture ir
section code    data align=8
    "mov {_end} _sp \{testlabel} \{data.end}"
  testlabel:
    "mov {_end + 1} _fp"
    "mov {testlabel} _ip"
  end:
section data data align=64
  hello: "hello,      日本語world!\n", 010203af
    "{2}\{code.end * 2}}\{data.hello}test", {a93d + hello * code.testlabel}, r"\\\\n", "\n"
    {2**8 - 1}, {a}, "\{a}", "{hello}   \{hello+1}"
    "this is a test\\\"\\", r"a\" simple test\\\"
    0, b,
    "\u65e5"
  end:
""")

for s in a.format.sections:
    print(str(s) + " (" + str(len(s.statements)) + "):")
    for stmt in s.statements:
        if type(stmt) == asm.data.data: print(stmt, stmt.labels)
        else: print(stmt)

